### ISSUE TITLE
Deploy and run the network

### ISSUE THREAD

**Issue by jt-cv** [FengyangZhang/caffe_roomnet#3]
Hello FengyangZhang,

thanks for sharing the code. I was able to train the network and get a model.
I'm trying to estimate the layout but the heatmaps and model type estimated are not good.
Do you have any script for this ?

My python script looks like this : 

model = 'roomnet_deploy.prototxt';
weights = 'snapshots_std5_swap_iter_100000.caffemodel';
net = caffe.Net(model, weights, caffe.TEST);
img = cv2.imread('IMG.jpg')
im = cv2.resize(img,(320,320),0,0,cv2.INTER_AREA)
input_image = im.transpose((2,0,1))
input_image = np.asarray([input_image])
res = net.forward(data=input_image)
heatmaps = res['heatmap_visualize']
prob = res['prob']

Thank you for your help.

**Comment by Fang-Haoshu** [comment]
Hi, I would also like to train the network. May you share the train.txt? We can work together to make this work

**Comment by Fang-Haoshu** [comment]
BTW, during testing, you might want to set_channel_swap('data', (2,1,0))  since the reference model has channels in BGR order instead of RGB

**Comment by jt-cv** [comment]
Hi,

yes let's make it work together.

Actually, the images are loaded in BGR order with opencv (imread) and then convert to RGB (see data_heatmap.cpp line 210). I did it but still get wrong results.

Regarding the training.txt file, each line corresponds to an image name with the room layout type and the keypoint coordinates. Example (room type 4) : 

sun_asmkptxcduixclmd.jpg 4 870.409711684,1133.83915023,99.5447647951,1600.0,866.767830046,0.0,1200.0,1206.676783

You can download the training set here : 
http://lsun.cs.princeton.edu/2015.html

Then, you need to read the training.mat file containing all the information and complete your training.txt file.

Hope that would help.

**Comment by Fang-Haoshu** [comment]
Yeah.

For any one in need, he can generate the 'train.txt' using this python script:
```
import scipy.io
mat = scipy.io.loadmat('training.mat')
file = open('train.txt','w')
for i in range(4000):
	file.write(str(mat['training'][0][i][0][0])+'.jpg')
	file.write(' ')
	file.write(str(mat['training'][0][i][2][0][0]))
	file.write(' ')
	for k in range(len(mat['training'][0][i][3])-1):
		file.write(str(mat['training'][0][i][3][k][0]))
		file.write(',')
		file.write(str(mat['training'][0][i][3][k][1]))
		file.write(',')
	file.write(str(mat['training'][0][i][3][len(mat['training'][0][i][3])-1][0]))
	file.write(',')
	file.write(str(mat['training'][0][i][3][len(mat['training'][0][i][3])-1][1]))
	file.write('\n')
file.close()
```

**Comment by Fang-Haoshu** [comment]
How about using the standard caffe io transformer like my previous project?
https://github.com/MVIG-SJTU/RMPE/blob/master/examples/rmpe/demo.py#L23

Do we need to re-scale the image to 0-255 or 0-1? And perhaps you wanna upload some output of you script so we can better debug?

**Comment by jt-cv** [comment]
Hi,

I've tried the data transformer but it doesn't improve the results. I have also checked the pixel values stored in data_heatmap.cpp and it seems to be 0-255.

Regarding the output I get after the forward() : 

 - output['prob'][0] :  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
Most of the time, I get the highest probability for the room layout type number 4

- output['heatmap_visualize']
All the Keypoint heatmaps are almost empty (zero values) except for heatmaps number 17, 18 and 19. However, those three heatmaps don't have the gaussian distribution expected.

Were you able to train the network ?

**Comment by jt-cv** [comment]
Ok, I have finally discovered what was wrong! The "roomnet_deploy.prototxt" works for a model trained with "roomnet_trained.prototxt". Since my model was trained using "roomnet_multistage.prototxt", I needed to write another prototxt file for deployment. You can find it attached (Note : I changed the extension because .prototxt was not accepted as attachment).
[roomnet_deploy_multistage.txt](https://github.com/FengyangZhang/caffe_roomnet/files/1241541/roomnet_deploy_multistage.txt)

**Comment by Fang-Haoshu** [comment]
I see, nice! Thanks.
